rtp_analyze_EXTRA_DIST = rtp_analyze
rtp_analyze_CLEANFILES = rtp_analyze_*.wav rtp_analyze_*.tout rtp_analyze_*.tlog \
  rtp_analyze_*.pcap
TESTS += rtp_analyze/rtp_analyze1 rtp_analyze/truncated
CLEANFILES += ${rtp_analyze_CLEANFILES}
EXTRA_DIST += ${rtp_analyze_EXTRA_DIST}
