#!/bin/sh

# test start up of rtpproxy and handling of SIGTERM and SIGHUP

BASEDIR="`dirname "${0}"`/.."
. "${BASEDIR}/functions"

TS_LOGFILE="startstop.nodebug.rlog"

. "${BASEDIR}/startstop/startstop.sub"

test_startstop "startstop.nodebug.rout" "${RTPPROXY_PROD}" "libucl/libucl_test.nodebug.conf" \
 "../modules/catch_dtmf/.libs/rtpp_catch_dtmf.so" "startstop.nodebug.output"
