#!/bin/sh

# test start up of rtpproxy and handling of SIGTERM and SIGHUP

BASEDIR="`dirname "${0}"`/.."
. "${BASEDIR}/functions"

TS_LOGFILE="startstop.rlog"

. "${BASEDIR}/startstop/startstop.sub"

test_startstop "startstop.rout" "${RTPPROXY_DBG}" "libucl/libucl_test.conf" \
 "../modules/acct_rtcp_hep/.libs/rtpp_acct_rtcp_hep_debug.so" "startstop.output"
