#!/bin/sh

# test start up of rtpproxy and handling of SIGTERM and SIGHUP

BASEDIR="`dirname "${0}"`/.."
. "${BASEDIR}/functions"

TS_LOGFILE="startstop.rlog"

__beforeexit_cleanup()
{
  if [ -f "${TMP_LOGFILE}" ]
  then
    cat "${TMP_LOGFILE}" >> "${TS_LOGFILE}"
    rm "${TMP_LOGFILE}"
  fi
}

RTPP_OUTFILE="startstop.rout"

truncate -s 0 "${TS_LOGFILE}"
for rargs in "" "--config libucl/libucl_test.conf"
do
  RTPP_ARGS="${rargs}" rtpproxy_start
  report "rtpproxy start"
  TMP_LOGFILE="/dev/null" rtpproxy_stop TERM
  report "rtpproxy stop (SIGTERM)"
  cat "${TMP_LOGFILE}" >> "${TS_LOGFILE}"
  rm "${TMP_LOGFILE}"
  ${DIFF} startstop/startstop.output startstop.rout
  report "rtpproxy output"
  RTPP_ARGS="${rargs}" rtpproxy_start
  report "rtpproxy start"
  TMP_LOGFILE="/dev/null" rtpproxy_stop HUP
  report "rtpproxy stop (SIGHUP)"
  cat "${TMP_LOGFILE}" >> "${TS_LOGFILE}"
  rm "${TMP_LOGFILE}"
  ${DIFF} startstop/startstop.output startstop.rout
  report "rtpproxy output"
done
