#!/bin/sh

# Test basic control protocol info commands. See basic_versions.input and
# basic_versions.output files for commands and expected results.

. $(dirname $0)/functions

for socket in ${RTPP_TEST_SOCKETS}
do
  if [ "${socket}" = "stdio:" ]
  then
    ${RTPPROXY} -f -s "${socket}" < $BASEDIR/basic_versions.input | \
      ${DIFF} ${BASEDIR}/basic_versions.output -
    report "basic_versions on ${socket}"
  else
    RTPP_SOCKFILE="${socket}" RTPP_OUTFILE="basic_versions.rout" rtpproxy_start
    report "rtpproxy start on ${socket}"
    ${RTPP_QUERY} -b -s "${socket}" \
      -S "${TOP_BUILDDIR}/python/sippy_lite" -i $BASEDIR/basic_versions.input -o basic_versions.qout
    report "rtpp_query on ${socket}"
    rtpproxy_stop HUP
    report "rtpproxy stop (SIGHUP) on ${socket}"
    cat basic_versions.qout basic_versions.rout | ${DIFF} ${BASEDIR}/basic_versions.output -
    report "basic_versions on ${socket}"
  fi
done
