#!/bin/sh

# checksum tests to verify that captured audio is correct.

. $(dirname $0)/functions

TKINDS="mono stereo"
OFMTS_mono="wav raw w64"
OFMTS_stereo="wav w64"

ofiles=""
extractaudio_RFILES="call2_ulaw call1_alaw call1_ulaw call1_g722 call1_g729 call1_gsm \
 call1_g722_srtp"

for tkind in ${TKINDS}
do
  if [ ${tkind} = "mono" ]
  then
    EXTRACTAUDIO_ARGS=""
    OFMTS="${OFMTS_mono}"
    CHFMT="m"
  else
    EXTRACTAUDIO_ARGS="-s"
    OFMTS="${OFMTS_stereo}"
    CHFMT="s"
  fi
  for rfile in ${extractaudio_RFILES}
  do
    for ofmt in ${OFMTS}
    do
      DFMTS=`cat extractaudio/extractaudio.${CHFMT}.${ofmt}.dfmts`
      for dfmt in ${DFMTS}
      do
        wfile="${rfile}.${tkind}.${dfmt}.${ofmt}"
        if [ -e "${wfile}" ]
        then
          rm "${wfile}"
        fi
        if [ -e "${rfile}.args" ]
        then
          EXTRACTAUDIO_EARGS=`cat "${rfile}.args"`
        else
          EXTRACTAUDIO_EARGS=""
        fi
        ${EXTRACTAUDIO} -F ${ofmt} -D ${dfmt} ${EXTRACTAUDIO_ARGS} \
         ${EXTRACTAUDIO_EARGS} ${rfile} ${wfile} 2>/dev/null >/dev/null || continue
        test -s ${wfile}
        report "${rfile} -> ${wfile}"
        sha256_verify ${wfile} extractaudio/extractaudio.checksums
      done
    done
  done
done
