#!/bin/sh

. $(dirname $0)/functions

PORTO=12344
CIDO=forwarding1_o_1
PORTA=$((${PORTO} - 2))
CIDA=forwarding1_a_1
TRASH_PORT1=63522
TRASH_PORT2=37822

FORWARDING_RFILES="forwarding1.0 forwarding1.3 forwarding1.8 forwarding1.18 forwarding1.9"
rm -f ${FORWARDING_RFILES}
${MAKEANN} ${BASEDIR}/ringback.sln ${BASEDIR}/forwarding1
report "makeann forwarding1"

for codeco in 0 3 8 18 9
do
  for codeca in 9 18 8 3 0
  do
    ${RTPPROXY} -T5 -b -s stdio: -s cunix:/tmp/forwarding1.sock -d info -f -m ${PORTA} < forwarding1.input > forwarding1.rout 2>/dev/null &
    FWD_PID=${!}
    ktrace -p ${FWD_PID} -f /var/tmp/rtpproxy.${FWD_PID}.ktrace
    (sleep 1; sed "s|%%CODEC%%|${codeco}| ; s|%%PORT1%%|${PORTO}| ; s|%%PORT2%%|${TRASH_PORT1}| ; s|%%CALLID%%|${CIDO}|" \
     forwarding1.gen.input) | ${RTPPROXY} -r `pwd` -T5 -b -m 12000 -s stdio: -f -d info > forwarding1.geno.rout 2>/dev/null &
    GENO_PID=${!}
    #ktrace -p ${GENO_PID} -f /var/tmp/rtpproxy.${GENO_PID}.ktrace
    (sleep 1; sed "s|%%CODEC%%|${codeca}| ; s|%%PORT1%%|${PORTA}| ; s|%%PORT2%%|${TRASH_PORT2}| ; s|%%CALLID%%|${CIDA}|" \
     forwarding1.gen.input) | ${RTPPROXY} -r `pwd` -T5 -b -m 15000 -s stdio: -f -d info > forwarding1.gena.rout 2>/dev/null &
    GENA_PID=${!}
    #ktrace -p ${GENA_PID} -f /var/tmp/rtpproxy.${GENA_PID}.ktrace
    wait ${FWD_PID}
    report "wait for rtpproxy Fwd shutdown, PID: ${FWD_PID}"
    wait ${GENO_PID}
    report "wait for rtpproxy Gen.O shutdown, PID: ${GENO_PID}"
    wait ${GENA_PID}
    report "wait for rtpproxy Gen.A shutdown, PID: ${GENA_PID}"
    ${DIFF} forwarding1.rout forwarding1.output
    report "checking rtpproxy stdout"
    ${DIFF} forwarding1.geno.rout forwarding1.geno.output
    report "checking rtpproxy.geno stdout"
    ${DIFF} forwarding1.gena.rout forwarding1.gena.output
    report "checking rtpproxy.gena stdout"
    rm -f forwarding1.${codeco}.wav
    ${EXTRACTAUDIO} -n -s forwarding1_a_1=from_tag_1 forwarding1.${codeco}.wav
    report "extractaudio forwarding1.${codeco}.wav"
    #sha256 forwarding1.${codeco}.wav
    sha256_verify forwarding1.${codeco}.wav forwarding1.checksums
    rm -f forwarding1.${codeca}.wav
    ${EXTRACTAUDIO} -n -s forwarding1_o_1=from_tag_1 forwarding1.${codeca}.wav
    report "extractaudio forwarding1.${codeca}.wav"
    sha256_verify forwarding1.${codeca}.wav forwarding1.checksums
    #sha256 forwarding1.${codeca}.wav
  done
done
