#!/bin/sh

. $(dirname $0)/functions

TESTDDIR="${BASEDIR}/libucl"

${TOP_BUILDDIR}/libucl/libucl_test ${TESTDDIR}/libucl_test.conf > ${BASEDIR}/libucl1.output
report "running libucl_test"
${DIFF} ${BASEDIR}/libucl1.output ${TESTDDIR}/libucl1.output
report "checking libucl1.output"

