#!/bin/sh

. $(dirname $0)/functions

TARGET_PORT=12344
RTPP_TIMEOUT=8
PLAYBACK_RFILES="playback1.0 playback1.3 playback1.8 playback1.18 playback1.9"
rm -f ${PLAYBACK_RFILES}
${MAKEANN} ${BASEDIR}/ringback.sln ${BASEDIR}/playback1
report "makeann playback1"

for delay in 0 1
do
  for codec in 0 3 8 18 9
  do
    if [ ${codec} -ne 3 ]
    then
      NPKTS=600
    else
      NPKTS=300
    fi
    ${SUDO} ${TCPDUMP} -w playback1.${codec}.a.rtp -s0 -ni ${LOOPBACK_INTERFACE} -c ${NPKTS} udp port ${TARGET_PORT} &
    TCPD_PID=${!}
    (sleep ${delay}; sed "s|%%CODEC%%|${codec}| ; s|%%PORT1%%|${TARGET_PORT}| ; s|%%PORT2%%|$((${TARGET_PORT} + 2))|" playback1.input) | \
     ${RTPPROXY} -T$((${RTPP_TIMEOUT} + ${delay})) -b -m 12000 -s stdio: -f -d info > playback1.rout 2>/dev/null &
    PLB_PID=${!}
    ##ktrace -p ${PLB_PID} -f /var/tmp/rtpproxy.${PLB_PID}.ktrace
    ##echo ${TCPD_PID}
    wait ${PLB_PID}
    report "wait for rtpproxy shutdown"
    kill -TERM ${TCPD_PID} 2>/dev/null
    reportifnotfail "wait for tcpdump shutdown"
    wait ${TCPD_PID}
    report "tcpdump playback1.${codec}.a.rtp"
    ofile="playback1.${codec}.wav"
    ${EXTRACTAUDIO} -n playback1.${codec} ${ofile} #>/dev/null 2>/dev/null
    report "extractaudio playback1.${codec} -> ${ofile}"
    #sha256 ${ofile}
    #report "sha256 ${ofile}"
    #wait
    ${DIFF} playback1.rout playback1.output
    report "checking rtpproxy stdout"
    sha256_verify ${ofile} playback1.checksums
  done
done
