#!/bin/sh

# checksum tests to verify that rtp_analyze routines work correctly

. $(dirname $0)/functions

SNAMES="sess6 c1 weird dups lost srtp1"

for sname in ${SNAMES}
do
  wfile="rtp_analyze_${sname}.wav"
  ${EXTRACTAUDIO} -s rtp_analyze/${sname} "${wfile}" > rtp_analyze_${sname}.tout 2>rtp_analyze_${sname}.tlog
  ${DIFF} rtp_analyze/${sname}.output rtp_analyze_${sname}.tout
  report "checking stats for the ${sname}"
  sha256_verify "${wfile}" rtp_analyze/rtp_analyze1.checksums
done
