#!/bin/sh

. $(dirname $0)/functions

rtpproxy_start
report "rtpproxy start"
kill -TERM `cat ${TMP_PIDFILE}`
sleep 1
if [ -e ${TMP_PIDFILE} ]
then
  kill -KILL `cat ${TMP_PIDFILE}`
  fail "rtpproxy stop (SIGTERM)"
fi
report "rtpproxy stop (SIGTERM)"
rtpproxy_start
report "rtpproxy start"
kill -HUP `cat ${TMP_PIDFILE}`
sleep 1
if [ -e ${TMP_PIDFILE} ]
then
  kill -KILL `cat ${TMP_PIDFILE}`
  fail "rtpproxy stop (SIGHUP)"
fi
report "rtpproxy stop (SIGHUP)"
