/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_ttl.h"
#include "rtpp_ttl_fin.h"
static void rtpp_ttl_decr_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ttl@%p::decr (rtpp_ttl_decr) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ttl_get_remaining_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ttl@%p::get_remaining (rtpp_ttl_get_remaining) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ttl_reset_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ttl@%p::reset (rtpp_ttl_reset) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ttl_reset_with_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ttl@%p::reset_with (rtpp_ttl_reset_with) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_ttl_smethods rtpp_ttl_smethods_fin = {
    .decr = (rtpp_ttl_decr_t)&rtpp_ttl_decr_fin,
    .get_remaining = (rtpp_ttl_get_remaining_t)&rtpp_ttl_get_remaining_fin,
    .reset = (rtpp_ttl_reset_t)&rtpp_ttl_reset_fin,
    .reset_with = (rtpp_ttl_reset_with_t)&rtpp_ttl_reset_with_fin,
};
void rtpp_ttl_fin(struct rtpp_ttl *pub) {
    RTPP_DBG_ASSERT(pub->smethods->decr != (rtpp_ttl_decr_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->get_remaining != (rtpp_ttl_get_remaining_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->reset != (rtpp_ttl_reset_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->reset_with != (rtpp_ttl_reset_with_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_ttl_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_ttl_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_ttl_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_ttl pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_ttl_smethods dummy = {
        .decr = (rtpp_ttl_decr_t)((void *)0x1),
        .get_remaining = (rtpp_ttl_get_remaining_t)((void *)0x1),
        .reset = (rtpp_ttl_reset_t)((void *)0x1),
        .reset_with = (rtpp_ttl_reset_with_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_ttl_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, decr);
    CALL_TFIN(&tp->pub, get_remaining);
    CALL_TFIN(&tp->pub, reset);
    CALL_TFIN(&tp->pub, reset_with);
    assert((_naborts - naborts_s) == 4);
}
DATA_SET(rtpp_fintests, rtpp_ttl_fintest);
#endif /* RTPP_FINTEST */
