/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_packetport_fin_h)
#define _rtpp_packetport_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_packetport_int;
void rtpp_packetport_int_fin(struct rtpp_packetport_int *);
#else
#define rtpp_packetport_int_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_packetport_int_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_packetport_fin_h */
