/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_log_obj_fin_h)
#define _rtpp_log_obj_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_log;
void rtpp_log_fin(struct rtpp_log *);
#else
#define rtpp_log_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_log_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_log_obj_fin_h */
