/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_server_fin_h)
#define _rtpp_server_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_server_fin(struct rtpp_server *);
#endif /* _rtpp_server_fin_h */
