/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_pipe.h"
#include "rtpp_pipe_fin.h"
static void rtpp_pipe_decr_ttl_fin(void *pub) {
    fprintf(stderr, "Method rtpp_pipe@%p::decr_ttl (rtpp_pipe_decr_ttl) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_pipe_get_stats_fin(void *pub) {
    fprintf(stderr, "Method rtpp_pipe@%p::get_stats (rtpp_pipe_get_stats) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_pipe_get_ttl_fin(void *pub) {
    fprintf(stderr, "Method rtpp_pipe@%p::get_ttl (rtpp_pipe_get_ttl) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_pipe_upd_cntrs_fin(void *pub) {
    fprintf(stderr, "Method rtpp_pipe@%p::upd_cntrs (rtpp_pipe_upd_cntrs) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_pipe_smethods rtpp_pipe_smethods_fin = {
    .decr_ttl = (rtpp_pipe_decr_ttl_t)&rtpp_pipe_decr_ttl_fin,
    .get_stats = (rtpp_pipe_get_stats_t)&rtpp_pipe_get_stats_fin,
    .get_ttl = (rtpp_pipe_get_ttl_t)&rtpp_pipe_get_ttl_fin,
    .upd_cntrs = (rtpp_pipe_upd_cntrs_t)&rtpp_pipe_upd_cntrs_fin,
};
void rtpp_pipe_fin(struct rtpp_pipe *pub) {
    RTPP_DBG_ASSERT(pub->smethods->decr_ttl != (rtpp_pipe_decr_ttl_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->get_stats != (rtpp_pipe_get_stats_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->get_ttl != (rtpp_pipe_get_ttl_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->upd_cntrs != (rtpp_pipe_upd_cntrs_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_pipe_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_pipe_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_pipe_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_pipe pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_pipe_smethods dummy = {
        .decr_ttl = (rtpp_pipe_decr_ttl_t)((void *)0x1),
        .get_stats = (rtpp_pipe_get_stats_t)((void *)0x1),
        .get_ttl = (rtpp_pipe_get_ttl_t)((void *)0x1),
        .upd_cntrs = (rtpp_pipe_upd_cntrs_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_pipe_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, decr_ttl);
    CALL_TFIN(&tp->pub, get_stats);
    CALL_TFIN(&tp->pub, get_ttl);
    CALL_TFIN(&tp->pub, upd_cntrs);
    assert((_naborts - naborts_s) == 4);
}
DATA_SET(rtpp_fintests, rtpp_pipe_fintest);
#endif /* RTPP_FINTEST */
