/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_rw_lock.h"
#include "rtpp_rw_lock_fin.h"
static void rtpp_rw_lock_lock_fin(void *pub) {
    fprintf(stderr, "Method rtpp_rw_lock@%p::lock (rtpp_rw_lock_lock) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_rw_lock_unlock_fin(void *pub) {
    fprintf(stderr, "Method rtpp_rw_lock@%p::unlock (rtpp_rw_lock_unlock) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_rw_lock_upgrade_fin(void *pub) {
    fprintf(stderr, "Method rtpp_rw_lock@%p::upgrade (rtpp_rw_lock_upgrade) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_rw_lock_smethods rtpp_rw_lock_smethods_fin = {
    .lock = (rtpp_rw_lock_lock_t)&rtpp_rw_lock_lock_fin,
    .unlock = (rtpp_rw_lock_unlock_t)&rtpp_rw_lock_unlock_fin,
    .upgrade = (rtpp_rw_lock_upgrade_t)&rtpp_rw_lock_upgrade_fin,
};
void rtpp_rw_lock_fin(struct rtpp_rw_lock *pub) {
    RTPP_DBG_ASSERT(pub->smethods->lock != (rtpp_rw_lock_lock_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->unlock != (rtpp_rw_lock_unlock_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->upgrade != (rtpp_rw_lock_upgrade_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_rw_lock_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_rw_lock_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_rw_lock_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_rw_lock pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_rw_lock_smethods dummy = {
        .lock = (rtpp_rw_lock_lock_t)((void *)0x1),
        .unlock = (rtpp_rw_lock_unlock_t)((void *)0x1),
        .upgrade = (rtpp_rw_lock_upgrade_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_rw_lock_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, lock);
    CALL_TFIN(&tp->pub, unlock);
    CALL_TFIN(&tp->pub, upgrade);
    assert((_naborts - naborts_s) == 3);
}
DATA_SET(rtpp_fintests, rtpp_rw_lock_fintest);
#endif /* RTPP_FINTEST */
