/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_socket.h"
#include "rtpp_socket_fin.h"
static void rtpp_socket_bind_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::bind2 (rtpp_socket_bind) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_drain_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::drain (rtpp_socket_drain) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_get_stuid_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::get_stuid (rtpp_socket_get_stuid) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_getfd_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::getfd (rtpp_socket_getfd) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_rtp_recv_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::rtp_recv (rtpp_socket_rtp_recv) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_send_pkt_na_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::send_pkt_na (rtpp_socket_send_pkt_na) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_set_stuid_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::set_stuid (rtpp_socket_set_stuid) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_setnonblock_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::setnonblock (rtpp_socket_setnonblock) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_setrbuf_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::setrbuf (rtpp_socket_setrbuf) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_settimestamp_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::settimestamp (rtpp_socket_settimestamp) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_socket_settos_fin(void *pub) {
    fprintf(stderr, "Method rtpp_socket@%p::settos (rtpp_socket_settos) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_socket_smethods rtpp_socket_smethods_fin = {
    .bind2 = (rtpp_socket_bind_t)&rtpp_socket_bind_fin,
    .drain = (rtpp_socket_drain_t)&rtpp_socket_drain_fin,
    .get_stuid = (rtpp_socket_get_stuid_t)&rtpp_socket_get_stuid_fin,
    .getfd = (rtpp_socket_getfd_t)&rtpp_socket_getfd_fin,
    .rtp_recv = (rtpp_socket_rtp_recv_t)&rtpp_socket_rtp_recv_fin,
    .send_pkt_na = (rtpp_socket_send_pkt_na_t)&rtpp_socket_send_pkt_na_fin,
    .set_stuid = (rtpp_socket_set_stuid_t)&rtpp_socket_set_stuid_fin,
    .setnonblock = (rtpp_socket_setnonblock_t)&rtpp_socket_setnonblock_fin,
    .setrbuf = (rtpp_socket_setrbuf_t)&rtpp_socket_setrbuf_fin,
    .settimestamp = (rtpp_socket_settimestamp_t)&rtpp_socket_settimestamp_fin,
    .settos = (rtpp_socket_settos_t)&rtpp_socket_settos_fin,
};
void rtpp_socket_fin(struct rtpp_socket *pub) {
    RTPP_DBG_ASSERT(pub->smethods->bind2 != (rtpp_socket_bind_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->drain != (rtpp_socket_drain_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->get_stuid != (rtpp_socket_get_stuid_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->getfd != (rtpp_socket_getfd_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->rtp_recv != (rtpp_socket_rtp_recv_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->send_pkt_na != (rtpp_socket_send_pkt_na_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->set_stuid != (rtpp_socket_set_stuid_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->setnonblock != (rtpp_socket_setnonblock_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->setrbuf != (rtpp_socket_setrbuf_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->settimestamp != (rtpp_socket_settimestamp_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->settos != (rtpp_socket_settos_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_socket_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_socket_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_socket_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_socket pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_socket_smethods dummy = {
        .bind2 = (rtpp_socket_bind_t)((void *)0x1),
        .drain = (rtpp_socket_drain_t)((void *)0x1),
        .get_stuid = (rtpp_socket_get_stuid_t)((void *)0x1),
        .getfd = (rtpp_socket_getfd_t)((void *)0x1),
        .rtp_recv = (rtpp_socket_rtp_recv_t)((void *)0x1),
        .send_pkt_na = (rtpp_socket_send_pkt_na_t)((void *)0x1),
        .set_stuid = (rtpp_socket_set_stuid_t)((void *)0x1),
        .setnonblock = (rtpp_socket_setnonblock_t)((void *)0x1),
        .setrbuf = (rtpp_socket_setrbuf_t)((void *)0x1),
        .settimestamp = (rtpp_socket_settimestamp_t)((void *)0x1),
        .settos = (rtpp_socket_settos_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_socket_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, bind2);
    CALL_TFIN(&tp->pub, drain);
    CALL_TFIN(&tp->pub, get_stuid);
    CALL_TFIN(&tp->pub, getfd);
    CALL_TFIN(&tp->pub, rtp_recv);
    CALL_TFIN(&tp->pub, send_pkt_na);
    CALL_TFIN(&tp->pub, set_stuid);
    CALL_TFIN(&tp->pub, setnonblock);
    CALL_TFIN(&tp->pub, setrbuf);
    CALL_TFIN(&tp->pub, settimestamp);
    CALL_TFIN(&tp->pub, settos);
    assert((_naborts - naborts_s) == 11);
}
DATA_SET(rtpp_fintests, rtpp_socket_fintest);
#endif /* RTPP_FINTEST */
