/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_server.h"
static void rtpp_server_get_fin(void *pub) {
    fprintf(stderr, "Method rtpp_server_get is called after destruction\x0a");
    abort();
}
static void rtpp_server_get_seq_fin(void *pub) {
    fprintf(stderr, "Method rtpp_server_get_seq is called after destruction\x0a");
    abort();
}
static void rtpp_server_get_ssrc_fin(void *pub) {
    fprintf(stderr, "Method rtpp_server_get_ssrc is called after destruction\x0a");
    abort();
}
static void rtpp_server_set_seq_fin(void *pub) {
    fprintf(stderr, "Method rtpp_server_set_seq is called after destruction\x0a");
    abort();
}
static void rtpp_server_set_ssrc_fin(void *pub) {
    fprintf(stderr, "Method rtpp_server_set_ssrc is called after destruction\x0a");
    abort();
}
static void rtpp_server_start_fin(void *pub) {
    fprintf(stderr, "Method rtpp_server_start is called after destruction\x0a");
    abort();
}
static const struct rtpp_server_smethods rtpp_server_smethods_fin = {
    . get = (rtpp_server_get_t)&rtpp_server_get_fin,
    . get_ssrc = (rtpp_server_get_ssrc_t)&rtpp_server_get_ssrc_fin,
    . set_ssrc = (rtpp_server_set_ssrc_t)&rtpp_server_set_ssrc_fin,
    . get_seq = (rtpp_server_get_seq_t)&rtpp_server_get_seq_fin,
    . set_seq = (rtpp_server_set_seq_t)&rtpp_server_set_seq_fin,
    . start = (rtpp_server_start_t)&rtpp_server_start_fin,
};
void rtpp_server_fin(struct rtpp_server *pub) {
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_server_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_server_smethods_fin;
}
