/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_pcnt_strm_fin_h)
#define _rtpp_pcnt_strm_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_pcnt_strm_fin(struct rtpp_pcnt_strm *);
#if defined(RTPP_FINTEST)
void rtpp_pcnt_strm_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_pcnt_strm_fin_h */
