/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_pipe_fin_h)
#define _rtpp_pipe_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_pipe_fin(struct rtpp_pipe *);
#endif /* _rtpp_pipe_fin_h */
