/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_netaddr_fin_h)
#define _rtpp_netaddr_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_netaddr_fin(struct rtpp_netaddr *);
#if defined(RTPP_FINTEST)
void rtpp_netaddr_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_netaddr_fin_h */
