/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_proc_servers.h"
#include "rtpp_proc_servers_fin.h"
static void rtpp_proc_servers_plr_start_fin(void *pub) {
    fprintf(stderr, "Method rtpp_proc_servers@%p::plr_start (rtpp_proc_servers_plr_start) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_proc_servers_reg_fin(void *pub) {
    fprintf(stderr, "Method rtpp_proc_servers@%p::reg (rtpp_proc_servers_reg) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_proc_servers_unreg_fin(void *pub) {
    fprintf(stderr, "Method rtpp_proc_servers@%p::unreg (rtpp_proc_servers_unreg) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_proc_servers_smethods rtpp_proc_servers_smethods_fin = {
    .plr_start = (rtpp_proc_servers_plr_start_t)&rtpp_proc_servers_plr_start_fin,
    .reg = (rtpp_proc_servers_reg_t)&rtpp_proc_servers_reg_fin,
    .unreg = (rtpp_proc_servers_unreg_t)&rtpp_proc_servers_unreg_fin,
};
void rtpp_proc_servers_fin(struct rtpp_proc_servers *pub) {
    RTPP_DBG_ASSERT(pub->smethods->plr_start != (rtpp_proc_servers_plr_start_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->reg != (rtpp_proc_servers_reg_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->unreg != (rtpp_proc_servers_unreg_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_proc_servers_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_proc_servers_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_proc_servers_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_proc_servers pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_proc_servers_smethods dummy = {
        .plr_start = (rtpp_proc_servers_plr_start_t)((void *)0x1),
        .reg = (rtpp_proc_servers_reg_t)((void *)0x1),
        .unreg = (rtpp_proc_servers_unreg_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_proc_servers_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, plr_start);
    CALL_TFIN(&tp->pub, reg);
    CALL_TFIN(&tp->pub, unreg);
    assert((_naborts - naborts_s) == 3);
}
DATA_SET(rtpp_fintests, rtpp_proc_servers_fintest);
#endif /* RTPP_FINTEST */
