/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_port_table.h"
#include "rtpp_port_table_fin.h"
#if defined(RTPP_DEBUG)
static void rtpp_ptbl_get_port_fin(void *pub) {
    fprintf(stderr, "Method rtpp_port_table@%p::get_port (rtpp_ptbl_get_port) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
void rtpp_port_table_fin(struct rtpp_port_table *pub) {
    RTPP_DBG_ASSERT(pub->get_port != (rtpp_ptbl_get_port_t)NULL);
    RTPP_DBG_ASSERT(pub->get_port != (rtpp_ptbl_get_port_t)&rtpp_ptbl_get_port_fin);
    pub->get_port = (rtpp_ptbl_get_port_t)&rtpp_ptbl_get_port_fin;
}
#endif /* RTPP_DEBUG */
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->fn))(pub)

void
rtpp_port_table_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_port_table pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    tp->pub.get_port = (rtpp_ptbl_get_port_t)((void *)0x1);
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_port_table_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, get_port);
    assert((_naborts - naborts_s) == 1);
}
DATA_SET(rtpp_fintests, rtpp_port_table_fintest);
#endif /* RTPP_FINTEST */
