/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_ringbuf.h"
#include "rtpp_ringbuf_fin.h"
static void rtpp_ringbuf_flush_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ringbuf@%p::flush (rtpp_ringbuf_flush) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ringbuf_locate_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ringbuf@%p::locate (rtpp_ringbuf_locate) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ringbuf_push_fin(void *pub) {
    fprintf(stderr, "Method rtpp_ringbuf@%p::push (rtpp_ringbuf_push) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_ringbuf_smethods rtpp_ringbuf_smethods_fin = {
    .flush = (rtpp_ringbuf_flush_t)&rtpp_ringbuf_flush_fin,
    .locate = (rtpp_ringbuf_locate_t)&rtpp_ringbuf_locate_fin,
    .push = (rtpp_ringbuf_push_t)&rtpp_ringbuf_push_fin,
};
void rtpp_ringbuf_fin(struct rtpp_ringbuf *pub) {
    RTPP_DBG_ASSERT(pub->smethods->flush != (rtpp_ringbuf_flush_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->locate != (rtpp_ringbuf_locate_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->push != (rtpp_ringbuf_push_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_ringbuf_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_ringbuf_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_ringbuf_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_ringbuf pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_ringbuf_smethods dummy = {
        .flush = (rtpp_ringbuf_flush_t)((void *)0x1),
        .locate = (rtpp_ringbuf_locate_t)((void *)0x1),
        .push = (rtpp_ringbuf_push_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_ringbuf_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, flush);
    CALL_TFIN(&tp->pub, locate);
    CALL_TFIN(&tp->pub, push);
    assert((_naborts - naborts_s) == 3);
}
DATA_SET(rtpp_fintests, rtpp_ringbuf_fintest);
#endif /* RTPP_FINTEST */
