/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_genuid.h"
#include "rtpp_genuid_fin.h"
static void rtpp_genuid_gen_fin(void *pub) {
    fprintf(stderr, "Method rtpp_genuid@%p::gen (rtpp_genuid_gen) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_genuid_smethods rtpp_genuid_smethods_fin = {
    .gen = (rtpp_genuid_gen_t)&rtpp_genuid_gen_fin,
};
void rtpp_genuid_fin(struct rtpp_genuid *pub) {
    RTPP_DBG_ASSERT(pub->smethods->gen != (rtpp_genuid_gen_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_genuid_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_genuid_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_genuid_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_genuid pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_genuid_smethods dummy = {
        .gen = (rtpp_genuid_gen_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    CALL_SMETHOD(tp->pub.rcnt, attach, (rtpp_refcnt_dtor_t)&rtpp_genuid_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, gen);
    assert((_naborts - naborts_s) == 1);
}
DATA_SET(rtpp_fintests, rtpp_genuid_fintest);
#endif /* RTPP_FINTEST */
