/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_wref_fin_h)
#define _rtpp_wref_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_wref;
void rtpp_wref_fin(struct rtpp_wref *);
#else
#define rtpp_wref_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_wref_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_wref_fin_h */
