/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_command_reply_fin_h)
#define _rtpp_command_reply_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpc_reply;
void rtpc_reply_fin(struct rtpc_reply *);
#else
#define rtpc_reply_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpc_reply_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_command_reply_fin_h */
