/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "rtpp_types.h"
#include "rtpp_debug.h"
#define rtpp_log_obj_h_fin 1
#include "rtpp_log_obj.h"
static void rtpp_log_ewrite_fin(void *pub) {
    fprintf(stderr, "Method rtpp_log_ewrite is called after destruction\x0a");
    abort();
}
static void rtpp_log_setlevel_fin(void *pub) {
    fprintf(stderr, "Method rtpp_log_setlevel is called after destruction\x0a");
    abort();
}
static void rtpp_log_start_fin(void *pub) {
    fprintf(stderr, "Method rtpp_log_start is called after destruction\x0a");
    abort();
}
static void rtpp_log_write_fin(void *pub) {
    fprintf(stderr, "Method rtpp_log_write is called after destruction\x0a");
    abort();
}
void rtpp_log_fin(struct rtpp_log *pub) {
    RTPP_DBG_ASSERT(pub-> write != (rtpp_log_write_t)&rtpp_log_write_fin);
    pub-> write = (rtpp_log_write_t)&rtpp_log_write_fin;
    RTPP_DBG_ASSERT(pub-> ewrite != (rtpp_log_ewrite_t)&rtpp_log_ewrite_fin);
    pub-> ewrite = (rtpp_log_ewrite_t)&rtpp_log_ewrite_fin;
    RTPP_DBG_ASSERT(pub-> setlevel != (rtpp_log_setlevel_t)&rtpp_log_setlevel_fin);
    pub-> setlevel = (rtpp_log_setlevel_t)&rtpp_log_setlevel_fin;
    RTPP_DBG_ASSERT(pub-> start != (rtpp_log_start_t)&rtpp_log_start_fin);
    pub-> start = (rtpp_log_start_t)&rtpp_log_start_fin;
}
