/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_wref.h"
#include "rtpp_wref_fin.h"
static void rtpp_wref_getref_fin(void *pub) {
    fprintf(stderr, "Method rtpp_wref@%p::getref (rtpp_wref_getref) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_wref_setref_fin(void *pub) {
    fprintf(stderr, "Method rtpp_wref@%p::setref (rtpp_wref_setref) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_wref_smethods rtpp_wref_smethods_fin = {
    .getref = (rtpp_wref_getref_t)&rtpp_wref_getref_fin,
    .setref = (rtpp_wref_setref_t)&rtpp_wref_setref_fin,
};
void rtpp_wref_fin(struct rtpp_wref *pub) {
    RTPP_DBG_ASSERT(pub->smethods->getref != (rtpp_wref_getref_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->setref != (rtpp_wref_setref_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_wref_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_wref_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_wref_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_wref pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_wref_smethods dummy = {
        .getref = (rtpp_wref_getref_t)((void *)0x1),
        .setref = (rtpp_wref_setref_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    RTPP_OBJ_DTOR_ATTACH_s(&tp->pub, (rtpp_refcnt_dtor_t)&rtpp_wref_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, getref);
    CALL_TFIN(&tp->pub, setref);
    assert((_naborts - naborts_s) == 2);
}
DATA_SET(rtpp_fintests, rtpp_wref_fintest);
#endif /* RTPP_FINTEST */
