/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_sessinfo_fin_h)
#define _rtpp_sessinfo_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_sessinfo_fin(struct rtpp_sessinfo *);
#endif /* _rtpp_sessinfo_fin_h */
