/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_record.h"
#include "rtpp_record_fin.h"
static void rtpp_record_write_fin(void *pub) {
    fprintf(stderr, "Method %p->write (rtpp_record_write) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
void rtpp_record_fin(struct rtpp_record *pub) {
    RTPP_DBG_ASSERT(pub->write != (rtpp_record_write_t)&rtpp_record_write_fin);
    pub->write = (rtpp_record_write_t)&rtpp_record_write_fin;
}
