/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_hash_table_fin_h)
#define _rtpp_hash_table_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_hash_table;
void rtpp_hash_table_fin(struct rtpp_hash_table *);
#else
#define rtpp_hash_table_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_hash_table_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_hash_table_fin_h */
