/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_pearson_perfect_fin_h)
#define _rtpp_pearson_perfect_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_pearson_perfect_fin(struct rtpp_pearson_perfect *);
#if defined(RTPP_FINTEST)
void rtpp_pearson_perfect_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_pearson_perfect_fin_h */
