/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_module_if_fin_h)
#define _rtpp_module_if_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_module_if_fin(struct rtpp_module_if *);
#if defined(RTPP_FINTEST)
void rtpp_module_if_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_module_if_fin_h */
