/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_sessinfo_fin_h)
#define _rtpp_sessinfo_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_sessinfo;
void rtpp_sessinfo_fin(struct rtpp_sessinfo *);
#else
#define rtpp_sessinfo_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_sessinfo_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_sessinfo_fin_h */
