/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_port_table_fin_h)
#define _rtpp_port_table_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_port_table_fin(struct rtpp_port_table *);
#endif /* _rtpp_port_table_fin_h */
