/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_packetport.h"
#include "rtpp_packetport_fin.h"
static void rtpp_packetport_next_in_port_fin(void *pub) {
    fprintf(stderr, "Method rtpp_packetport_int@%p::next_in_port (rtpp_packetport_next_in_port) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_packetport_next_out_port_fin(void *pub) {
    fprintf(stderr, "Method rtpp_packetport_int@%p::next_out_port (rtpp_packetport_next_out_port) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_packetport_reg_stream_fin(void *pub) {
    fprintf(stderr, "Method rtpp_packetport_int@%p::reg_stream (rtpp_packetport_reg_stream) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_packetport_reg_streams_fin(void *pub) {
    fprintf(stderr, "Method rtpp_packetport_int@%p::reg_streams (rtpp_packetport_reg_streams) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_packetport_send_pkt_na_fin(void *pub) {
    fprintf(stderr, "Method rtpp_packetport_int@%p::send_pkt_na (rtpp_packetport_send_pkt_na) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_packetport_unreg_stream_fin(void *pub) {
    fprintf(stderr, "Method rtpp_packetport_int@%p::unreg_stream (rtpp_packetport_unreg_stream) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_packetport_int_smethods rtpp_packetport_int_smethods_fin = {
    .next_in_port = (rtpp_packetport_next_in_port_t)&rtpp_packetport_next_in_port_fin,
    .next_out_port = (rtpp_packetport_next_out_port_t)&rtpp_packetport_next_out_port_fin,
    .reg_stream = (rtpp_packetport_reg_stream_t)&rtpp_packetport_reg_stream_fin,
    .reg_streams = (rtpp_packetport_reg_streams_t)&rtpp_packetport_reg_streams_fin,
    .send_pkt_na = (rtpp_packetport_send_pkt_na_t)&rtpp_packetport_send_pkt_na_fin,
    .unreg_stream = (rtpp_packetport_unreg_stream_t)&rtpp_packetport_unreg_stream_fin,
};
void rtpp_packetport_int_fin(struct rtpp_packetport_int *pub) {
    RTPP_DBG_ASSERT(pub->smethods->next_in_port != (rtpp_packetport_next_in_port_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->next_out_port != (rtpp_packetport_next_out_port_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->reg_stream != (rtpp_packetport_reg_stream_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->reg_streams != (rtpp_packetport_reg_streams_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->send_pkt_na != (rtpp_packetport_send_pkt_na_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->unreg_stream != (rtpp_packetport_unreg_stream_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_packetport_int_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_packetport_int_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_packetport_int_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_packetport_int pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_packetport_int_smethods dummy = {
        .next_in_port = (rtpp_packetport_next_in_port_t)((void *)0x1),
        .next_out_port = (rtpp_packetport_next_out_port_t)((void *)0x1),
        .reg_stream = (rtpp_packetport_reg_stream_t)((void *)0x1),
        .reg_streams = (rtpp_packetport_reg_streams_t)((void *)0x1),
        .send_pkt_na = (rtpp_packetport_send_pkt_na_t)((void *)0x1),
        .unreg_stream = (rtpp_packetport_unreg_stream_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    RTPP_OBJ_DTOR_ATTACH_s(&tp->pub, (rtpp_refcnt_dtor_t)&rtpp_packetport_int_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, next_in_port);
    CALL_TFIN(&tp->pub, next_out_port);
    CALL_TFIN(&tp->pub, reg_stream);
    CALL_TFIN(&tp->pub, reg_streams);
    CALL_TFIN(&tp->pub, send_pkt_na);
    CALL_TFIN(&tp->pub, unreg_stream);
    assert((_naborts - naborts_s) == 6);
}
DATA_SET(rtpp_fintests, rtpp_packetport_int_fintest);
#endif /* RTPP_FINTEST */
