/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_ttl.h"
#include "rtpp_ttl_fin.h"
static void rtpp_ttl_decr_fin(void *pub) {
    fprintf(stderr, "Method %p->decr (rtpp_ttl_decr) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ttl_get_remaining_fin(void *pub) {
    fprintf(stderr, "Method %p->get_remaining (rtpp_ttl_get_remaining) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ttl_reset_fin(void *pub) {
    fprintf(stderr, "Method %p->reset (rtpp_ttl_reset) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void rtpp_ttl_reset_with_fin(void *pub) {
    fprintf(stderr, "Method %p->reset_with (rtpp_ttl_reset_with) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
void rtpp_ttl_fin(struct rtpp_ttl *pub) {
    RTPP_DBG_ASSERT(pub->decr != (rtpp_ttl_decr_t)&rtpp_ttl_decr_fin);
    pub->decr = (rtpp_ttl_decr_t)&rtpp_ttl_decr_fin;
    RTPP_DBG_ASSERT(pub->get_remaining != (rtpp_ttl_get_remaining_t)&rtpp_ttl_get_remaining_fin);
    pub->get_remaining = (rtpp_ttl_get_remaining_t)&rtpp_ttl_get_remaining_fin;
    RTPP_DBG_ASSERT(pub->reset != (rtpp_ttl_reset_t)&rtpp_ttl_reset_fin);
    pub->reset = (rtpp_ttl_reset_t)&rtpp_ttl_reset_fin;
    RTPP_DBG_ASSERT(pub->reset_with != (rtpp_ttl_reset_with_t)&rtpp_ttl_reset_with_fin);
    pub->reset_with = (rtpp_ttl_reset_with_t)&rtpp_ttl_reset_with_fin;
}
