/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_port_table.h"
#include "rtpp_port_table_fin.h"
static void rtpp_ptbl_get_port_fin(void *pub) {
    fprintf(stderr, "Method %p->get_port (rtpp_ptbl_get_port) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
void rtpp_port_table_fin(struct rtpp_port_table *pub) {
    RTPP_DBG_ASSERT(pub->get_port != (rtpp_ptbl_get_port_t)&rtpp_ptbl_get_port_fin);
    pub->get_port = (rtpp_ptbl_get_port_t)&rtpp_ptbl_get_port_fin;
}
