/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_socket_fin_h)
#define _rtpp_socket_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_socket;
void rtpp_socket_fin(struct rtpp_socket *);
#else
#define rtpp_socket_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_socket_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_socket_fin_h */
