/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define RTPP_FINCODE
#include "rtpp_types.h"
#include "rtpp_debug.h"
#include "rtpp_bindaddrs.h"
#include "rtpp_bindaddrs_fin.h"
static void addr2bindaddr_fin(void *pub) {
    fprintf(stderr, "Method rtpp_bindaddrs@%p::addr2 (addr2bindaddr) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void bindaddr4af_fin(void *pub) {
    fprintf(stderr, "Method rtpp_bindaddrs@%p::foraf (bindaddr4af) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void host2bindaddr_fin(void *pub) {
    fprintf(stderr, "Method rtpp_bindaddrs@%p::host2 (host2bindaddr) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void label2bindaddr_fin(void *pub) {
    fprintf(stderr, "Method rtpp_bindaddrs@%p::label2 (label2bindaddr) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static void local4remote_fin(void *pub) {
    fprintf(stderr, "Method rtpp_bindaddrs@%p::local4remote (local4remote) is invoked after destruction\x0a", pub);
    RTPP_AUTOTRAP();
}
static const struct rtpp_bindaddrs_smethods rtpp_bindaddrs_smethods_fin = {
    .addr2 = (addr2bindaddr_t)&addr2bindaddr_fin,
    .foraf = (bindaddr4af_t)&bindaddr4af_fin,
    .host2 = (host2bindaddr_t)&host2bindaddr_fin,
    .label2 = (label2bindaddr_t)&label2bindaddr_fin,
    .local4remote = (local4remote_t)&local4remote_fin,
};
void rtpp_bindaddrs_fin(struct rtpp_bindaddrs *pub) {
    RTPP_DBG_ASSERT(pub->smethods->addr2 != (addr2bindaddr_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->foraf != (bindaddr4af_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->host2 != (host2bindaddr_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->label2 != (label2bindaddr_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods->local4remote != (local4remote_t)NULL);
    RTPP_DBG_ASSERT(pub->smethods != &rtpp_bindaddrs_smethods_fin &&
      pub->smethods != NULL);
    pub->smethods = &rtpp_bindaddrs_smethods_fin;
}
#if defined(RTPP_FINTEST)
#include <assert.h>
#include <stddef.h>
#include "rtpp_mallocs.h"
#include "rtpp_refcnt.h"
#include "rtpp_linker_set.h"
#define CALL_TFIN(pub, fn) ((void (*)(typeof(pub)))((pub)->smethods->fn))(pub)

void
rtpp_bindaddrs_fintest()
{
    int naborts_s;

    struct {
        struct rtpp_bindaddrs pub;
    } *tp;

    naborts_s = _naborts;
    tp = rtpp_rzmalloc(sizeof(*tp), offsetof(typeof(*tp), pub.rcnt));
    assert(tp != NULL);
    assert(tp->pub.rcnt != NULL);
    static const struct rtpp_bindaddrs_smethods dummy = {
        .addr2 = (addr2bindaddr_t)((void *)0x1),
        .foraf = (bindaddr4af_t)((void *)0x1),
        .host2 = (host2bindaddr_t)((void *)0x1),
        .label2 = (label2bindaddr_t)((void *)0x1),
        .local4remote = (local4remote_t)((void *)0x1),
    };
    tp->pub.smethods = &dummy;
    RTPP_OBJ_DTOR_ATTACH_s(&tp->pub, (rtpp_refcnt_dtor_t)&rtpp_bindaddrs_fin,
      &tp->pub);
    RTPP_OBJ_DECREF(&(tp->pub));
    CALL_TFIN(&tp->pub, addr2);
    CALL_TFIN(&tp->pub, foraf);
    CALL_TFIN(&tp->pub, host2);
    CALL_TFIN(&tp->pub, label2);
    CALL_TFIN(&tp->pub, local4remote);
    assert((_naborts - naborts_s) == 5);
}
DATA_SET(rtpp_fintests, rtpp_bindaddrs_fintest);
#endif /* RTPP_FINTEST */
