/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_pcount_fin_h)
#define _rtpp_pcount_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_pcount_fin(struct rtpp_pcount *);
#endif /* _rtpp_pcount_fin_h */
