/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_pcnt_strm_fin_h)
#define _rtpp_pcnt_strm_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_pcnt_strm;
void rtpp_pcnt_strm_fin(struct rtpp_pcnt_strm *);
#else
#define rtpp_pcnt_strm_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_pcnt_strm_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_pcnt_strm_fin_h */
