/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_modman_fin_h)
#define _rtpp_modman_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_modman;
void rtpp_modman_fin(struct rtpp_modman *);
#else
#define rtpp_modman_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_modman_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_modman_fin_h */
