/* Auto-generated by genfincode.sh - DO NOT EDIT! */
#if !defined(_rtpp_command_rcache_fin_h)
#define _rtpp_command_rcache_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
void rtpp_cmd_rcache_fin(struct rtpp_cmd_rcache *);
#endif /* _rtpp_command_rcache_fin_h */
