/* Auto-generated by genfincode_stat.sh - DO NOT EDIT! */
#if !defined(_rtpp_pipe_fin_h)
#define _rtpp_pipe_fin_h
#if !defined(RTPP_AUTOTRAP)
#define RTPP_AUTOTRAP() abort()
#else
extern int _naborts;
#endif
#if defined(RTPP_DEBUG)
struct rtpp_pipe;
void rtpp_pipe_fin(struct rtpp_pipe *);
#else
#define rtpp_pipe_fin(arg) /* nop */
#endif
#if defined(RTPP_FINTEST)
void rtpp_pipe_fintest(void);
#endif /* RTPP_FINTEST */
#endif /* _rtpp_pipe_fin_h */
