# syntax=docker/dockerfile:1.7-labs

ARG BASE_IMAGE
ARG BUILD_IMAGE
FROM $BUILD_IMAGE AS build
RUN rm -rf /rtpproxy && rm -rf /var/cache/*
FROM $BASE_IMAGE
LABEL maintainer="Maksym Sobolyev <sobomax@sippysoft.com>"

USER root

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /

COPY --from=build / /

ENTRYPOINT ["/usr/local/bin/rtpproxy", "-fF"]
