#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

export RTPP_TEST_SOCKETS="stdio: ${RTPP_NOTIFY_SOCK_TCP}"
glitch_test "command_parser/command_parser1" 12 command_parser.rlog
report "glitching command_parser/command_parser1"
