#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

rm -f glitch1.seen.ncout
touch glitch1.seen.ncout
for rsock in "stdio:" "${RTPP_NOTIFY_SOCK_TCP}"
do
  export RTPP_TEST_SOCKETS="${rsock}"
  glitch_collect "command_parser/command_parser1"
  report "Collecting glitch data for \"command_parser1/${rsock}\""
  grep -v -w -f glitch1.seen.ncout glitch1.ncout > glitch1.ncout_
  mv glitch1.ncout_ glitch1.ncout
  (awk '{print $2}' glitch1.ncout; cat glitch1.seen.ncout) | sort -u > glitch1.seen.ncout_
  mv glitch1.seen.ncout_ glitch1.seen.ncout
  UNSP=$((`awk '{print $2}' glitch1.ncout | sort -u | wc -l`))
  echo "                   ....${UNSP} unseen points"
  if [ ${rsock} = "stdio:" ]
  then
    NFPOS=13
  else
    NFPOS=0
  fi
  glitch_do "command_parser/command_parser1" ${NFPOS} command_parser.rlog
  report "glitching command_parser1/${rsock}"
done
