#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

glitch_test extractaudio/extractaudio1 7
report "glitching extractaudio/extractaudio1"
