#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

export RTPP_TEST_SOCKETS="stdio:"
glitch_test "command_parser/command_parser1" 20 command_parser.rlog
report "glitching command_parser/command_parser1"
