#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

glitch_test startstop/startstop1 0 startstop.rlog
report "glitching startstop/startstop1"
