#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

export RTPP_TEST_SOCKETS="stdio:"
glitch_test "command_parser/command_parser1" 6
report "glitching command_parser/command_parser1"
