#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

glitch_test acct_rtcp_hep/basic 16 acct_rtcp_hep.rlog
report "glitching acct_rtcp_hep/basic"
