#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

rm -f core
glitch_test catch_dtmf/basic 1 catch_dtmf.rlog 'rtpp_notify.c:206'
GL_RC=${?}
if [ -e core ]
then
  gdb --command=${BUILDDIR}/gdb.gettrace ${RTPPROXY} core >&2 && rm core
  GL_RC=1
fi
report_rc ${GL_RC} "glitching catch_dtmf/basic"
