#!/bin/sh

TDIR="`dirname "${0}"`"
BASEDIR="${TDIR}/.."
SUDO_REQUIRED=1
. "${BASEDIR}/functions"

. "${TDIR}/glitch.sub"

disable_aslr

glitch_test basic_versions/basic_versions1 24 basic_versions.rlog
report "glitching basic_versions/basic_versions1"
