memdeb_EXTRA_DIST = memdeb
memdeb_CLEANFILES = glitch1.ncout
TESTS += memdeb/glitch1 memdeb/glitch_startstop1 memdeb/glitch_basic_versions1
CLEANFILES += ${memdeb_CLEANFILES}
EXTRA_DIST += ${memdeb_EXTRA_DIST}
