unittests_EXTRA_DIST = unittests
rtcp2json_CLEANFILES = rtcp1.output
TESTS += unittests/rtcp2json1 unittests/rtpp_sbuf unittests/rtpp_objck
CLEANFILES += ${rtcp2json_CLEANFILES}
EXTRA_DIST += ${unittests_EXTRA_DIST}
