unittests_EXTRA_DIST = unittests
rtcp2json_CLEANFILES = rtcp1.output
if ENABLE_BASIC_TESTS
TESTS += unittests/rtcp2json1 unittests/rtpp_sbuf unittests/rtpp_objck \
  unittests/rtpp_rzmalloc_perf unittests/rtpp_fintest
endif
CLEANFILES += ${rtcp2json_CLEANFILES}
EXTRA_DIST += ${unittests_EXTRA_DIST}
