extractaudio_EXTRA_DIST = extractaudio
extractaudio_CLEANFILES = *.mono.*.wav *.stereo.*.wav *.mono.*.wav.tout \
  *.stereo.*.wav.tout *.mono.*.raw *.mono.*.raw.tout *.mono.*.w64 \
  *.mono.*.w64.tout *.stereo.*.w64 *.stereo.*.w64.tout \
  *.mono.*.rlog *.stereo.*.rlog
TESTS += extractaudio/badargs extractaudio/extractaudio1
CLEANFILES += ${extractaudio_CLEANFILES}
EXTRA_DIST += ${extractaudio_EXTRA_DIST}
