#!/bin/sh

set -e

TDIR="`dirname "${0}"`"
. "${TDIR}/genfincode.sub"

gen_fin_c() {
  echo "/* Auto-generated by ${GENRNAME} - DO NOT EDIT! */"
  echo "#include <stdio.h>"
  echo "#include <stdint.h>"
  echo "#include <stdlib.h>"
  echo "#include \"rtpp_types.h\""
  echo "#include \"rtpp_debug.h\""
  DEFNAME=`echo ${1} | sed 's|[.]|_|g'`
  echo "#define ${DEFNAME}_fin 1"
  echo "#include \"${1}\""

  for mname in ${MNAMES_ALL}
  do
    epname=`get_epname "${1}" "${mname}"`
    emit_finfunction "${mname}" "${epname}"
  done
  for oname in ${ONAMES}
  do
    echo "void ${oname}_fin(struct ${oname} *pub) {"
    MNAMES=`grep ^DEFINE_METHOD "${1}" | sed 's|^DEFINE_METHOD[(]||' | \
     grep "${oname}," | awk -F ',' '{print $2}' | sed 's|^[ ]*||' | \
     LC_ALL=C sort`
    for mname in ${MNAMES}
    do
      epname=`get_epname "${1}" "${mname}"`
      echo "    RTPP_DBG_ASSERT(pub->${epname} != (${mname}_t)&${mname}_fin);"
      echo "    pub->${epname} = (${mname}_t)&${mname}_fin;"
    done
    echo "}"
  done
}

emit_fin_h "${1}" > "${2}"
gen_fin_c "${1}" > "${3}"
